/* create tables to store raw data */
set ansi_nulls on
go

set quoted_identifier on
go
DROP TABLE IF EXISTS sql_scoring
GO

create table sql_scoring
(
transactionID varchar(255),
accountID varchar(255),
transactionAmountUSD varchar(255),
transactionAmount varchar(255),
transactionCurrencyCode varchar(255),
transactionCurrencyConversionRate varchar(255),
transactionDate varchar(255),
localHour varchar(255),
transactionScenario varchar(255),
transactionType varchar(255),
transactionMethod varchar(255),
transactionDeviceType varchar(255),
transactionDeviceId varchar(255),
transactionIPaddress varchar(255),
ipState varchar(255),
ipPostcode varchar(255),
ipCountryCode varchar(255),
isProxyIP varchar(255),
browserType varchar(255),
browserLanguage varchar(255),
paymentInstrumentType varchar(255),
cardType varchar(255),
cardNumberInputMethod varchar(255),
paymentInstrumentID varchar(255),
paymentBillingAddress varchar(255),
paymentBillingPostalCode varchar(255),
paymentBillingState varchar(255),
paymentBillingCountryCode varchar(255),
paymentBillingName varchar(255),
shippingAddress varchar(255),
shippingPostalCode varchar(255),
shippingCity varchar(255),
shippingState varchar(255),
shippingCountry varchar(255),
cvvVerifyResult varchar(255),
responseCode varchar(255),
digitalItemCount varchar(255),
physicalItemCount varchar(255),
purchaseProductType varchar(255),
accountOwnerName varchar(255),
accountAddress varchar(255),
accountPostalCode varchar(255),
accountCity varchar(255),
accountState varchar(255),
accountCountry varchar(255),
accountOpenDate varchar(255),
accountAge varchar(255),
isUserRegistered varchar(255),
paymentInstrumentAgeInAccount varchar(255),
sumPurchaseAmount1dPerUser varchar(255),
sumPurchaseAmount30dPerUser varchar(255),
sumPurchaseCount1dPerUser varchar(255),
sumPurchaseCount30dPerUser varchar(255),
numPaymentRejects1dPerUser varchar(255),
transactionTime_new varchar(255),
Label int,
dateNtime datetime,
timeFlag int,
random_number int,
trainFlag int,
is_highAmount varchar(255),
acct_billing_address_mismatchFlag varchar(255),
acct_billing_postalCode_mismatchFlag varchar(255),
acct_billing_country_mismatchFlag varchar(255),
acct_billing_name_mismatchFlag varchar(255),
acct_shipping_address_mismatchFlag varchar(255),
acct_shipping_postalCode_mismatchFlag varchar(255),
acct_shipping_country_mismatchFlag varchar(255),
shipping_billing_address_mismatchFlag varchar(255),
shipping_billing_postalCode_mismatchFlag varchar(255),
shipping_billing_country_mismatchFlag varchar(255),
transactionCurrencyCode_risk float,
localHour_risk float,
ipState_risk float,
ipPostCode_risk float,
ipCountryCode_risk float,
browserLanguage_risk float,
paymentBillingPostalCode_risk float,
paymentBillingState_risk float,
paymentBillingCountryCode_risk float,
shippingPostalCode_risk float,
shippingState_risk float,
shippingCountry_risk float,
accountPostalCode_risk float,
accountState_risk float,
accountCountry_risk float
);
